name: Scanners

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  npm_build:
    runs-on: ubuntu-latest
    name: NPM Build and Lint
    steps:
      - uses: actions/checkout@v2
      - name: npm Build
        run: npm install
      - run: set -eo pipefail; npm run build && npm run lint 2>&1| tee ./linter-report.txt
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: NPM Linter Report
          path: ./linter-report.txt

  npm_prettier:
    runs-on: ubuntu-latest
    name: NPM Prettier
    steps:
      - uses: actions/checkout@v2
      - name: npm Build
        run: npm install
      - run: set -eo pipefail; npm run prettier 2>&1| tee ./prettier-report.txt
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: NPM Prettier Report
          path: ./prettier-report.txt

  salus_security:
    runs-on: ubuntu-latest
    name: Salus
    steps:
      - uses: actions/checkout@v2
      - name: Salus Scan
        id: salus_scan
        uses: federacy/scan-action@0.1.4
        env:
          SALUS_CONFIGURATION: "file://salus-config.yaml"
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Salus report
          path: ./salus-report.txt
